# Simple Netlify Configuration that works

[build]
  # Since we're deploying static HTML + serverless functions
  # We'll copy files to dist directory
  command = "mkdir -p dist && cp *.html dist/ && cp *.js dist/ && cp -r backend dist/"
  publish = "dist"

  # Skip functions for now to get basic deployment working
  # functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"