# Simple Netlify Configuration that works

[build]
  # Build command that copies all necessary files including browser SQLite implementation
  command = "mkdir -p dist && cp *.html dist/ && cp *.js dist/ && cp -r src dist/ && cp -r backend dist/"
  publish = "dist"

  # Skip functions for now to get basic deployment working
  # functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Cache-Control = "public, max-age=31536000, immutable"

# Enable CORS for SQLite WASM worker
[[headers]]
  for = "/src/database/workers/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"